import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import BaseLayout from "../components/BaseLayout";
import withAuth from "../hocs/withAuth";
import withAuthServerSideProps from "../hocs/withAuthServerSideProps";

const Home: NextPage<{}> = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>메인화면</BaseLayout>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<{}> = withAuthServerSideProps<{}>();

export default withAuth(Home);
